### PR TITLE
feat: changed native_step of charge_current_limit due to nrgkick app …

### PR DESCRIPTION
**Pull request by fano0001**
Hi,
i found a toggle in the NRGKick APP today, to toggle the steps to set the current charge limit from int to float.

So it is possible via the NRGKick APP to set the ampere value to e.g. 14.5

### CODE REVIEW

**Comment by dupondje** [comment]
But, if you don't have the setting enabled, does setting a float value via HA work? Otherwise we need to check the value of the setting first.

**Comment by fano0001** [comment]
Will check it tomorrow, but i think its only a setting in the NRGKick app

**Comment by fano0001** [comment]
Any problems with the PR?

**Comment by dupondje** [comment]
I forgot honestly. Sorry for that!

**Pull request merged**
